### ISSUE TITLE
How do you configure links? 

### ISSUE THREAD

**Issue by erawhctim** [AndyReifman/LinkMagic#12]
What value should be used within the link as a replacement parameter? 

Your example screenshot shows `www.jira.com/browse/{p...`, I'm assuming the plugin expects something in the format link `{}` but I'm not sure what the value should be. 

Should this be called out more explicitly in the README? 😅

**Comment by erawhctim** [comment]
Figured it out: `{pattern}` for anyone else wondering

**Comment by MMoMM-org** [comment]
you shouldn't have closed the issue.. the readme needs to be updated.
