### ISSUE TITLE
Links include surrounding parentheses

### ISSUE THREAD

**Issue by erawhctim** [AndyReifman/LinkMagic#13]
Assuming I set up a regex rule like this: `APP-[\d+]` & `www.jira.com/{pattern}`, if I type `APP-1234` I get a link that looks like `www.jira.com/APP-1234` ✅  
works great!

However, If I type `(APP-1234)`, I get a link text like `[(APP-1234)](www.jira.com/(APP-1234))`, which seems like a bug? 

I would expect the parentheses to wrap the entire link like this: `([APP-1234](www.jira.com/APP-1234))`

**Comment by AndyReifman** [comment]
This should be fixed in the newest release (1.0.7)

**Comment by erawhctim** [comment]
amazing, thank you! great plugin!
